/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * AppPipelineStatus defines the observed state of AppPipeline
 * @export
 * @interface DevTsuzuModokiV1alpha1AppPipelineStatus
 */
export interface DevTsuzuModokiV1alpha1AppPipelineStatus {
    /**
     * Message is the detailed status or reason for the currnt status
     * @type {string}
     * @memberof DevTsuzuModokiV1alpha1AppPipelineStatus
     */
    message?: string;
}

export function DevTsuzuModokiV1alpha1AppPipelineStatusFromJSON(json: any): DevTsuzuModokiV1alpha1AppPipelineStatus {
    return DevTsuzuModokiV1alpha1AppPipelineStatusFromJSONTyped(json, false);
}

export function DevTsuzuModokiV1alpha1AppPipelineStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevTsuzuModokiV1alpha1AppPipelineStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function DevTsuzuModokiV1alpha1AppPipelineStatusToJSON(value?: DevTsuzuModokiV1alpha1AppPipelineStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}


