/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ApplicationSpec defines the desired state of Application
 * @export
 * @interface DevTsuzuModokiV1alpha1ApplicationSpec
 */
export interface DevTsuzuModokiV1alpha1ApplicationSpec {
    /**
     * Args is the arguments to the entrypoint
     * @type {Array<string>}
     * @memberof DevTsuzuModokiV1alpha1ApplicationSpec
     */
    args?: Array<string>;
    /**
     * Attributes is parameters for the generator
     * @type {{ [key: string]: string; }}
     * @memberof DevTsuzuModokiV1alpha1ApplicationSpec
     */
    attributes?: { [key: string]: string; };
    /**
     * Command is an entrypoint array
     * @type {Array<string>}
     * @memberof DevTsuzuModokiV1alpha1ApplicationSpec
     */
    command?: Array<string>;
    /**
     * Domains are requested domains for the ingress of the application
     * @type {Array<string>}
     * @memberof DevTsuzuModokiV1alpha1ApplicationSpec
     */
    domains: Array<string>;
    /**
     * Image is the url for Docker registry
     * @type {string}
     * @memberof DevTsuzuModokiV1alpha1ApplicationSpec
     */
    image: string;
}

export function DevTsuzuModokiV1alpha1ApplicationSpecFromJSON(json: any): DevTsuzuModokiV1alpha1ApplicationSpec {
    return DevTsuzuModokiV1alpha1ApplicationSpecFromJSONTyped(json, false);
}

export function DevTsuzuModokiV1alpha1ApplicationSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevTsuzuModokiV1alpha1ApplicationSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'args': !exists(json, 'args') ? undefined : json['args'],
        'attributes': !exists(json, 'attributes') ? undefined : json['attributes'],
        'command': !exists(json, 'command') ? undefined : json['command'],
        'domains': json['domains'],
        'image': json['image'],
    };
}

export function DevTsuzuModokiV1alpha1ApplicationSpecToJSON(value?: DevTsuzuModokiV1alpha1ApplicationSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'args': value.args,
        'attributes': value.attributes,
        'command': value.command,
        'domains': value.domains,
        'image': value.image,
    };
}


