/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DevTsuzuModokiV1alpha1AppPipeline,
    DevTsuzuModokiV1alpha1AppPipelineFromJSON,
    DevTsuzuModokiV1alpha1AppPipelineFromJSONTyped,
    DevTsuzuModokiV1alpha1AppPipelineToJSON,
    DevTsuzuModokiV1alpha1RemoteSyncListMetadata,
    DevTsuzuModokiV1alpha1RemoteSyncListMetadataFromJSON,
    DevTsuzuModokiV1alpha1RemoteSyncListMetadataFromJSONTyped,
    DevTsuzuModokiV1alpha1RemoteSyncListMetadataToJSON,
} from './';

/**
 * AppPipelineList is a list of AppPipeline
 * @export
 * @interface DevTsuzuModokiV1alpha1AppPipelineList
 */
export interface DevTsuzuModokiV1alpha1AppPipelineList {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof DevTsuzuModokiV1alpha1AppPipelineList
     */
    apiVersion?: string;
    /**
     * List of apppipelines. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
     * @type {Array<DevTsuzuModokiV1alpha1AppPipeline>}
     * @memberof DevTsuzuModokiV1alpha1AppPipelineList
     */
    items: Array<DevTsuzuModokiV1alpha1AppPipeline>;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof DevTsuzuModokiV1alpha1AppPipelineList
     */
    kind?: string;
    /**
     * 
     * @type {DevTsuzuModokiV1alpha1RemoteSyncListMetadata}
     * @memberof DevTsuzuModokiV1alpha1AppPipelineList
     */
    metadata?: DevTsuzuModokiV1alpha1RemoteSyncListMetadata;
}

export function DevTsuzuModokiV1alpha1AppPipelineListFromJSON(json: any): DevTsuzuModokiV1alpha1AppPipelineList {
    return DevTsuzuModokiV1alpha1AppPipelineListFromJSONTyped(json, false);
}

export function DevTsuzuModokiV1alpha1AppPipelineListFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevTsuzuModokiV1alpha1AppPipelineList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'items': ((json['items'] as Array<any>).map(DevTsuzuModokiV1alpha1AppPipelineFromJSON)),
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : DevTsuzuModokiV1alpha1RemoteSyncListMetadataFromJSON(json['metadata']),
    };
}

export function DevTsuzuModokiV1alpha1AppPipelineListToJSON(value?: DevTsuzuModokiV1alpha1AppPipelineList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'items': ((value.items as Array<any>).map(DevTsuzuModokiV1alpha1AppPipelineToJSON)),
        'kind': value.kind,
        'metadata': DevTsuzuModokiV1alpha1RemoteSyncListMetadataToJSON(value.metadata),
    };
}


