/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
 * @export
 * @interface DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadata
 */
export interface DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadata {
    /**
     * Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations
     * @type {{ [key: string]: string; }}
     * @memberof DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadata
     */
    annotations?: { [key: string]: string; };
    /**
     * Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels
     * @type {{ [key: string]: string; }}
     * @memberof DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadata
     */
    labels?: { [key: string]: string; };
}

export function DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadataFromJSON(json: any): DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadata {
    return DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadataFromJSONTyped(json, false);
}

export function DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'annotations': !exists(json, 'annotations') ? undefined : json['annotations'],
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
    };
}

export function DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadataToJSON(value?: DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'annotations': value.annotations,
        'labels': value.labels,
    };
}


