/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DevTsuzuModokiV1alpha1ApplicationSpec,
    DevTsuzuModokiV1alpha1ApplicationSpecFromJSON,
    DevTsuzuModokiV1alpha1ApplicationSpecFromJSONTyped,
    DevTsuzuModokiV1alpha1ApplicationSpecToJSON,
    DevTsuzuModokiV1alpha1ApplicationStatus,
    DevTsuzuModokiV1alpha1ApplicationStatusFromJSON,
    DevTsuzuModokiV1alpha1ApplicationStatusFromJSONTyped,
    DevTsuzuModokiV1alpha1ApplicationStatusToJSON,
    V1ObjectMeta,
    V1ObjectMetaFromJSON,
    V1ObjectMetaFromJSONTyped,
    V1ObjectMetaToJSON,
} from './';

/**
 * Application is the Schema for the applications API
 * @export
 * @interface DevTsuzuModokiV1alpha1Application
 */
export interface DevTsuzuModokiV1alpha1Application {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof DevTsuzuModokiV1alpha1Application
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof DevTsuzuModokiV1alpha1Application
     */
    kind?: string;
    /**
     * 
     * @type {V1ObjectMeta}
     * @memberof DevTsuzuModokiV1alpha1Application
     */
    metadata?: V1ObjectMeta;
    /**
     * 
     * @type {DevTsuzuModokiV1alpha1ApplicationSpec}
     * @memberof DevTsuzuModokiV1alpha1Application
     */
    spec?: DevTsuzuModokiV1alpha1ApplicationSpec;
    /**
     * 
     * @type {DevTsuzuModokiV1alpha1ApplicationStatus}
     * @memberof DevTsuzuModokiV1alpha1Application
     */
    status?: DevTsuzuModokiV1alpha1ApplicationStatus;
}

export function DevTsuzuModokiV1alpha1ApplicationFromJSON(json: any): DevTsuzuModokiV1alpha1Application {
    return DevTsuzuModokiV1alpha1ApplicationFromJSONTyped(json, false);
}

export function DevTsuzuModokiV1alpha1ApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevTsuzuModokiV1alpha1Application {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : V1ObjectMetaFromJSON(json['metadata']),
        'spec': !exists(json, 'spec') ? undefined : DevTsuzuModokiV1alpha1ApplicationSpecFromJSON(json['spec']),
        'status': !exists(json, 'status') ? undefined : DevTsuzuModokiV1alpha1ApplicationStatusFromJSON(json['status']),
    };
}

export function DevTsuzuModokiV1alpha1ApplicationToJSON(value?: DevTsuzuModokiV1alpha1Application | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': V1ObjectMetaToJSON(value.metadata),
        'spec': DevTsuzuModokiV1alpha1ApplicationSpecToJSON(value.spec),
        'status': DevTsuzuModokiV1alpha1ApplicationStatusToJSON(value.status),
    };
}


