/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadata,
    DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadataFromJSON,
    DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadataFromJSONTyped,
    DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadataToJSON,
    DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateSpec,
    DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateSpecFromJSON,
    DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateSpecFromJSONTyped,
    DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateSpecToJSON,
} from './';

/**
 * 
 * @export
 * @interface DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplate
 */
export interface DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplate {
    /**
     * 
     * @type {DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadata}
     * @memberof DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplate
     */
    metadata?: DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadata;
    /**
     * 
     * @type {DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateSpec}
     * @memberof DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplate
     */
    spec?: DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateSpec;
}

export function DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateFromJSON(json: any): DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplate {
    return DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateFromJSONTyped(json, false);
}

export function DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': !exists(json, 'metadata') ? undefined : DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadataFromJSON(json['metadata']),
        'spec': !exists(json, 'spec') ? undefined : DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateSpecFromJSON(json['spec']),
    };
}

export function DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateToJSON(value?: DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateMetadataToJSON(value.metadata),
        'spec': DevTsuzuModokiV1alpha1AppPipelineSpecApplicationTemplateSpecToJSON(value.spec),
    };
}


