/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FlowcontrolV1alpha1Subject,
    FlowcontrolV1alpha1SubjectFromJSON,
    FlowcontrolV1alpha1SubjectFromJSONTyped,
    FlowcontrolV1alpha1SubjectToJSON,
    V1alpha1NonResourcePolicyRule,
    V1alpha1NonResourcePolicyRuleFromJSON,
    V1alpha1NonResourcePolicyRuleFromJSONTyped,
    V1alpha1NonResourcePolicyRuleToJSON,
    V1alpha1ResourcePolicyRule,
    V1alpha1ResourcePolicyRuleFromJSON,
    V1alpha1ResourcePolicyRuleFromJSONTyped,
    V1alpha1ResourcePolicyRuleToJSON,
} from './';

/**
 * PolicyRulesWithSubjects prescribes a test that applies to a request to an apiserver. The test considers the subject making the request, the verb being requested, and the resource to be acted upon. This PolicyRulesWithSubjects matches a request if and only if both (a) at least one member of subjects matches the request and (b) at least one member of resourceRules or nonResourceRules matches the request.
 * @export
 * @interface V1alpha1PolicyRulesWithSubjects
 */
export interface V1alpha1PolicyRulesWithSubjects {
    /**
     * `nonResourceRules` is a list of NonResourcePolicyRules that identify matching requests according to their verb and the target non-resource URL.
     * @type {Array<V1alpha1NonResourcePolicyRule>}
     * @memberof V1alpha1PolicyRulesWithSubjects
     */
    nonResourceRules?: Array<V1alpha1NonResourcePolicyRule>;
    /**
     * `resourceRules` is a slice of ResourcePolicyRules that identify matching requests according to their verb and the target resource. At least one of `resourceRules` and `nonResourceRules` has to be non-empty.
     * @type {Array<V1alpha1ResourcePolicyRule>}
     * @memberof V1alpha1PolicyRulesWithSubjects
     */
    resourceRules?: Array<V1alpha1ResourcePolicyRule>;
    /**
     * subjects is the list of normal user, serviceaccount, or group that this rule cares about. There must be at least one member in this slice. A slice that includes both the system:authenticated and system:unauthenticated user groups matches every request. Required.
     * @type {Array<FlowcontrolV1alpha1Subject>}
     * @memberof V1alpha1PolicyRulesWithSubjects
     */
    subjects: Array<FlowcontrolV1alpha1Subject>;
}

export function V1alpha1PolicyRulesWithSubjectsFromJSON(json: any): V1alpha1PolicyRulesWithSubjects {
    return V1alpha1PolicyRulesWithSubjectsFromJSONTyped(json, false);
}

export function V1alpha1PolicyRulesWithSubjectsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1PolicyRulesWithSubjects {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nonResourceRules': !exists(json, 'nonResourceRules') ? undefined : ((json['nonResourceRules'] as Array<any>).map(V1alpha1NonResourcePolicyRuleFromJSON)),
        'resourceRules': !exists(json, 'resourceRules') ? undefined : ((json['resourceRules'] as Array<any>).map(V1alpha1ResourcePolicyRuleFromJSON)),
        'subjects': ((json['subjects'] as Array<any>).map(FlowcontrolV1alpha1SubjectFromJSON)),
    };
}

export function V1alpha1PolicyRulesWithSubjectsToJSON(value?: V1alpha1PolicyRulesWithSubjects | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nonResourceRules': value.nonResourceRules === undefined ? undefined : ((value.nonResourceRules as Array<any>).map(V1alpha1NonResourcePolicyRuleToJSON)),
        'resourceRules': value.resourceRules === undefined ? undefined : ((value.resourceRules as Array<any>).map(V1alpha1ResourcePolicyRuleToJSON)),
        'subjects': ((value.subjects as Array<any>).map(FlowcontrolV1alpha1SubjectToJSON)),
    };
}


