/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * FlowSchemaCondition describes conditions for a FlowSchema.
 * @export
 * @interface V1alpha1FlowSchemaCondition
 */
export interface V1alpha1FlowSchemaCondition {
    /**
     * `lastTransitionTime` is the last time the condition transitioned from one status to another.
     * @type {Date}
     * @memberof V1alpha1FlowSchemaCondition
     */
    lastTransitionTime?: Date;
    /**
     * `message` is a human-readable message indicating details about last transition.
     * @type {string}
     * @memberof V1alpha1FlowSchemaCondition
     */
    message?: string;
    /**
     * `reason` is a unique, one-word, CamelCase reason for the condition's last transition.
     * @type {string}
     * @memberof V1alpha1FlowSchemaCondition
     */
    reason?: string;
    /**
     * `status` is the status of the condition. Can be True, False, Unknown. Required.
     * @type {string}
     * @memberof V1alpha1FlowSchemaCondition
     */
    status?: string;
    /**
     * `type` is the type of the condition. Required.
     * @type {string}
     * @memberof V1alpha1FlowSchemaCondition
     */
    type?: string;
}

export function V1alpha1FlowSchemaConditionFromJSON(json: any): V1alpha1FlowSchemaCondition {
    return V1alpha1FlowSchemaConditionFromJSONTyped(json, false);
}

export function V1alpha1FlowSchemaConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1FlowSchemaCondition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastTransitionTime': !exists(json, 'lastTransitionTime') ? undefined : (new Date(json['lastTransitionTime'])),
        'message': !exists(json, 'message') ? undefined : json['message'],
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function V1alpha1FlowSchemaConditionToJSON(value?: V1alpha1FlowSchemaCondition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastTransitionTime': value.lastTransitionTime === undefined ? undefined : (value.lastTransitionTime.toISOString()),
        'message': value.message,
        'reason': value.reason,
        'status': value.status,
        'type': value.type,
    };
}


