/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * WebhookThrottleConfig holds the configuration for throttling events
 * @export
 * @interface V1alpha1WebhookThrottleConfig
 */
export interface V1alpha1WebhookThrottleConfig {
    /**
     * ThrottleBurst is the maximum number of events sent at the same moment default 15 QPS
     * @type {number}
     * @memberof V1alpha1WebhookThrottleConfig
     */
    burst?: number;
    /**
     * ThrottleQPS maximum number of batches per second default 10 QPS
     * @type {number}
     * @memberof V1alpha1WebhookThrottleConfig
     */
    qps?: number;
}

export function V1alpha1WebhookThrottleConfigFromJSON(json: any): V1alpha1WebhookThrottleConfig {
    return V1alpha1WebhookThrottleConfigFromJSONTyped(json, false);
}

export function V1alpha1WebhookThrottleConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1WebhookThrottleConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'burst': !exists(json, 'burst') ? undefined : json['burst'],
        'qps': !exists(json, 'qps') ? undefined : json['qps'],
    };
}

export function V1alpha1WebhookThrottleConfigToJSON(value?: V1alpha1WebhookThrottleConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'burst': value.burst,
        'qps': value.qps,
    };
}


