/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RbacV1alpha1Subject,
    RbacV1alpha1SubjectFromJSON,
    RbacV1alpha1SubjectFromJSONTyped,
    RbacV1alpha1SubjectToJSON,
    V1ObjectMeta,
    V1ObjectMetaFromJSON,
    V1ObjectMetaFromJSONTyped,
    V1ObjectMetaToJSON,
    V1alpha1RoleRef,
    V1alpha1RoleRefFromJSON,
    V1alpha1RoleRefFromJSONTyped,
    V1alpha1RoleRefToJSON,
} from './';

/**
 * ClusterRoleBinding references a ClusterRole, but not contain it.  It can reference a ClusterRole in the global namespace, and adds who information via Subject. Deprecated in v1.17 in favor of rbac.authorization.k8s.io/v1 ClusterRoleBinding, and will no longer be served in v1.20.
 * @export
 * @interface V1alpha1ClusterRoleBinding
 */
export interface V1alpha1ClusterRoleBinding {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1alpha1ClusterRoleBinding
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1alpha1ClusterRoleBinding
     */
    kind?: string;
    /**
     * 
     * @type {V1ObjectMeta}
     * @memberof V1alpha1ClusterRoleBinding
     */
    metadata?: V1ObjectMeta;
    /**
     * 
     * @type {V1alpha1RoleRef}
     * @memberof V1alpha1ClusterRoleBinding
     */
    roleRef: V1alpha1RoleRef;
    /**
     * Subjects holds references to the objects the role applies to.
     * @type {Array<RbacV1alpha1Subject>}
     * @memberof V1alpha1ClusterRoleBinding
     */
    subjects?: Array<RbacV1alpha1Subject>;
}

export function V1alpha1ClusterRoleBindingFromJSON(json: any): V1alpha1ClusterRoleBinding {
    return V1alpha1ClusterRoleBindingFromJSONTyped(json, false);
}

export function V1alpha1ClusterRoleBindingFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1ClusterRoleBinding {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : V1ObjectMetaFromJSON(json['metadata']),
        'roleRef': V1alpha1RoleRefFromJSON(json['roleRef']),
        'subjects': !exists(json, 'subjects') ? undefined : ((json['subjects'] as Array<any>).map(RbacV1alpha1SubjectFromJSON)),
    };
}

export function V1alpha1ClusterRoleBindingToJSON(value?: V1alpha1ClusterRoleBinding | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': V1ObjectMetaToJSON(value.metadata),
        'roleRef': V1alpha1RoleRefToJSON(value.roleRef),
        'subjects': value.subjects === undefined ? undefined : ((value.subjects as Array<any>).map(RbacV1alpha1SubjectToJSON)),
    };
}


