/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1ObjectMeta,
    V1ObjectMetaFromJSON,
    V1ObjectMetaFromJSONTyped,
    V1ObjectMetaToJSON,
    V1alpha1PodPresetSpec,
    V1alpha1PodPresetSpecFromJSON,
    V1alpha1PodPresetSpecFromJSONTyped,
    V1alpha1PodPresetSpecToJSON,
} from './';

/**
 * PodPreset is a policy resource that defines additional runtime requirements for a Pod.
 * @export
 * @interface V1alpha1PodPreset
 */
export interface V1alpha1PodPreset {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1alpha1PodPreset
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1alpha1PodPreset
     */
    kind?: string;
    /**
     * 
     * @type {V1ObjectMeta}
     * @memberof V1alpha1PodPreset
     */
    metadata?: V1ObjectMeta;
    /**
     * 
     * @type {V1alpha1PodPresetSpec}
     * @memberof V1alpha1PodPreset
     */
    spec?: V1alpha1PodPresetSpec;
}

export function V1alpha1PodPresetFromJSON(json: any): V1alpha1PodPreset {
    return V1alpha1PodPresetFromJSONTyped(json, false);
}

export function V1alpha1PodPresetFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1PodPreset {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : V1ObjectMetaFromJSON(json['metadata']),
        'spec': !exists(json, 'spec') ? undefined : V1alpha1PodPresetSpecFromJSON(json['spec']),
    };
}

export function V1alpha1PodPresetToJSON(value?: V1alpha1PodPreset | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': V1ObjectMetaToJSON(value.metadata),
        'spec': V1alpha1PodPresetSpecToJSON(value.spec),
    };
}


