/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ServiceAccountSubject holds detailed information for service-account-kind subject.
 * @export
 * @interface V1alpha1ServiceAccountSubject
 */
export interface V1alpha1ServiceAccountSubject {
    /**
     * `name` is the name of matching ServiceAccount objects, or "*" to match regardless of name. Required.
     * @type {string}
     * @memberof V1alpha1ServiceAccountSubject
     */
    name: string;
    /**
     * `namespace` is the namespace of matching ServiceAccount objects. Required.
     * @type {string}
     * @memberof V1alpha1ServiceAccountSubject
     */
    namespace: string;
}

export function V1alpha1ServiceAccountSubjectFromJSON(json: any): V1alpha1ServiceAccountSubject {
    return V1alpha1ServiceAccountSubjectFromJSONTyped(json, false);
}

export function V1alpha1ServiceAccountSubjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1ServiceAccountSubject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'namespace': json['namespace'],
    };
}

export function V1alpha1ServiceAccountSubjectToJSON(value?: V1alpha1ServiceAccountSubject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'namespace': value.namespace,
    };
}


