/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1ObjectMeta,
    V1ObjectMetaFromJSON,
    V1ObjectMetaFromJSONTyped,
    V1ObjectMetaToJSON,
    V1beta1LeaseSpec,
    V1beta1LeaseSpecFromJSON,
    V1beta1LeaseSpecFromJSONTyped,
    V1beta1LeaseSpecToJSON,
} from './';

/**
 * Lease defines a lease concept.
 * @export
 * @interface V1beta1Lease
 */
export interface V1beta1Lease {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1beta1Lease
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1beta1Lease
     */
    kind?: string;
    /**
     * 
     * @type {V1ObjectMeta}
     * @memberof V1beta1Lease
     */
    metadata?: V1ObjectMeta;
    /**
     * 
     * @type {V1beta1LeaseSpec}
     * @memberof V1beta1Lease
     */
    spec?: V1beta1LeaseSpec;
}

export function V1beta1LeaseFromJSON(json: any): V1beta1Lease {
    return V1beta1LeaseFromJSONTyped(json, false);
}

export function V1beta1LeaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1Lease {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : V1ObjectMetaFromJSON(json['metadata']),
        'spec': !exists(json, 'spec') ? undefined : V1beta1LeaseSpecFromJSON(json['spec']),
    };
}

export function V1beta1LeaseToJSON(value?: V1beta1Lease | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': V1ObjectMetaToJSON(value.metadata),
        'spec': V1beta1LeaseSpecToJSON(value.spec),
    };
}


