/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * APIServiceCondition describes the state of an APIService at a particular point
 * @export
 * @interface V1beta1APIServiceCondition
 */
export interface V1beta1APIServiceCondition {
    /**
     * Last time the condition transitioned from one status to another.
     * @type {Date}
     * @memberof V1beta1APIServiceCondition
     */
    lastTransitionTime?: Date;
    /**
     * Human-readable message indicating details about last transition.
     * @type {string}
     * @memberof V1beta1APIServiceCondition
     */
    message?: string;
    /**
     * Unique, one-word, CamelCase reason for the condition's last transition.
     * @type {string}
     * @memberof V1beta1APIServiceCondition
     */
    reason?: string;
    /**
     * Status is the status of the condition. Can be True, False, Unknown.
     * @type {string}
     * @memberof V1beta1APIServiceCondition
     */
    status: string;
    /**
     * Type is the type of the condition.
     * @type {string}
     * @memberof V1beta1APIServiceCondition
     */
    type: string;
}

export function V1beta1APIServiceConditionFromJSON(json: any): V1beta1APIServiceCondition {
    return V1beta1APIServiceConditionFromJSONTyped(json, false);
}

export function V1beta1APIServiceConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1APIServiceCondition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastTransitionTime': !exists(json, 'lastTransitionTime') ? undefined : (new Date(json['lastTransitionTime'])),
        'message': !exists(json, 'message') ? undefined : json['message'],
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
        'status': json['status'],
        'type': json['type'],
    };
}

export function V1beta1APIServiceConditionToJSON(value?: V1beta1APIServiceCondition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastTransitionTime': value.lastTransitionTime === undefined ? undefined : (value.lastTransitionTime.toISOString()),
        'message': value.message,
        'reason': value.reason,
        'status': value.status,
        'type': value.type,
    };
}


