/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1ListMeta,
    V1ListMetaFromJSON,
    V1ListMetaFromJSONTyped,
    V1ListMetaToJSON,
    V1beta1CSIDriver,
    V1beta1CSIDriverFromJSON,
    V1beta1CSIDriverFromJSONTyped,
    V1beta1CSIDriverToJSON,
} from './';

/**
 * CSIDriverList is a collection of CSIDriver objects.
 * @export
 * @interface V1beta1CSIDriverList
 */
export interface V1beta1CSIDriverList {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1beta1CSIDriverList
     */
    apiVersion?: string;
    /**
     * items is the list of CSIDriver
     * @type {Array<V1beta1CSIDriver>}
     * @memberof V1beta1CSIDriverList
     */
    items: Array<V1beta1CSIDriver>;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1beta1CSIDriverList
     */
    kind?: string;
    /**
     * 
     * @type {V1ListMeta}
     * @memberof V1beta1CSIDriverList
     */
    metadata?: V1ListMeta;
}

export function V1beta1CSIDriverListFromJSON(json: any): V1beta1CSIDriverList {
    return V1beta1CSIDriverListFromJSONTyped(json, false);
}

export function V1beta1CSIDriverListFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1CSIDriverList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'items': ((json['items'] as Array<any>).map(V1beta1CSIDriverFromJSON)),
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : V1ListMetaFromJSON(json['metadata']),
    };
}

export function V1beta1CSIDriverListToJSON(value?: V1beta1CSIDriverList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'items': ((value.items as Array<any>).map(V1beta1CSIDriverToJSON)),
        'kind': value.kind,
        'metadata': V1ListMetaToJSON(value.metadata),
    };
}


