/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * NetworkPolicyPort describes a port to allow traffic on
 * @export
 * @interface V1NetworkPolicyPort
 */
export interface V1NetworkPolicyPort {
    /**
     * The port on the given protocol. This can either be a numerical or named port on a pod. If this field is not provided, this matches all port names and numbers.
     * @type {object}
     * @memberof V1NetworkPolicyPort
     */
    port?: object;
    /**
     * The protocol (TCP, UDP, or SCTP) which traffic must match. If not specified, this field defaults to TCP.
     * @type {string}
     * @memberof V1NetworkPolicyPort
     */
    protocol?: string;
}

export function V1NetworkPolicyPortFromJSON(json: any): V1NetworkPolicyPort {
    return V1NetworkPolicyPortFromJSONTyped(json, false);
}

export function V1NetworkPolicyPortFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1NetworkPolicyPort {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'port': !exists(json, 'port') ? undefined : json['port'],
        'protocol': !exists(json, 'protocol') ? undefined : json['protocol'],
    };
}

export function V1NetworkPolicyPortToJSON(value?: V1NetworkPolicyPort | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'port': value.port,
        'protocol': value.protocol,
    };
}


