/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1LoadBalancerStatus,
    V1LoadBalancerStatusFromJSON,
    V1LoadBalancerStatusFromJSONTyped,
    V1LoadBalancerStatusToJSON,
} from './';

/**
 * ServiceStatus represents the current status of a service.
 * @export
 * @interface V1ServiceStatus
 */
export interface V1ServiceStatus {
    /**
     * 
     * @type {V1LoadBalancerStatus}
     * @memberof V1ServiceStatus
     */
    loadBalancer?: V1LoadBalancerStatus;
}

export function V1ServiceStatusFromJSON(json: any): V1ServiceStatus {
    return V1ServiceStatusFromJSONTyped(json, false);
}

export function V1ServiceStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ServiceStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'loadBalancer': !exists(json, 'loadBalancer') ? undefined : V1LoadBalancerStatusFromJSON(json['loadBalancer']),
    };
}

export function V1ServiceStatusToJSON(value?: V1ServiceStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'loadBalancer': V1LoadBalancerStatusToJSON(value.loadBalancer),
    };
}


