name: Docker
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  operator:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        export CLIENT_ROOT=`pwd`
        export GENERATED_DIR=$(mktemp -d)
        npm set init.license "MIT"
        cd $(mktemp -d)
        git clone https://github.com/kubernetes-client/gen.git
        cd gen
        cp ${CLIENT_ROOT}/config/typescript-fetch.* ./openapi/
        ./openapi/typescript-fetch.sh ${GENERATED_DIR} ${CLIENT_ROOT}/config/settings.sh
        cat ${GENERATED_DIR}/package.json
        jq -s '.[0] + .[1]' ${GENERATED_DIR}/package.json ${CLIENT_ROOT}/config/package.template.json > ${GENERATED_DIR}/package.json
        cat ${GENERATED_DIR}/package.json
        cp -r ${GENERATED_DIR}/* ${CLIENT_ROOT}/
        cd ${CLIENT_ROOT}
        ls -la
        git status
        cat package.json
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update typescript-fetch
        title: Update typescript-fetch
        branch: update-typescript