name: Docker
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  operator:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Build
      run: |
        export CLIENT_ROOT=`pwd`
        export GENERATED_DIR=$(mktemp -d)
        npm set init.license "MIT"
        cd $(mktemp -d)
        git clone https://github.com/kubernetes-client/gen.git
        cd gen
        cp ${CLIENT_ROOT}/config/typescript-fetch.* ./openapi/
        ./openapi/typescript-fetch.sh ${GENERATED_DIR} ${CLIENT_ROOT}/config/settings.sh
        cat ${GENERATED_DIR}/package.json
        export TMP=$(mktemp)
        jq -s '.[0] * .[1]' ${GENERATED_DIR}/package.json ${CLIENT_ROOT}/config/package.template.json > $TMP && cp $TMP ${GENERATED_DIR}/package.json
        jq -s '.[0] * .[1]' ${GENERATED_DIR}/tsconfig.json ${CLIENT_ROOT}/config/tsconfig.template.json > $TMP && cp $TMP ${GENERATED_DIR}/tsconfig.json
        rm -r ${CLIENT_ROOT}/src
        cp -r ${GENERATED_DIR}/* ${CLIENT_ROOT}/
        cd ${CLIENT_ROOT}

        npm i --only=dev typescript@4.0.2
        npm run build

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update typescript-fetch
        title: Update typescript-fetch
        branch: update-typescript